version: "3.5"
services:
  gin_fileserver:
    build: .
    image: accalina/gin_pdfserver:1.1
    container_name: gin_pdfserver
    volumes:
      - './data:/api/public/'
    ports:
      - "7002:8090"
